sudo: required
services:
  - docker

before_install:
  - docker build -t eddiedj/react-test -f ./clent/dev.Dockerfile ./client

script:
  - docker run -e CI=true eddiedj/react-test npm test -- --coverage

after_success:
  - docker build -t eddiedj/multi-client ./client
  - docker build -t eddiedj/multi-nginx ./nginx
  - docker build -t eddiedj/multi-server ./server
  - docker build -t eddiedj/multi-worker ./worker
  # Log into Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stadin
  # Take those images and push them to docker hub
  - docker push eddiedj/multi-client
  - docker push eddiedj/multi-nginx
  - docker push eddiedj/multi-server
  - docker push eddiedj/multi-worker
